# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12e701b0384935f5dc4852916a6a88c9e30f6e9cec4fe7b79993b6c58b544cf6d7eb64f9ba5d1f68ec71a7b797f0285fb1f9d9cd63b256322b71ec18ed20bef3

test:
  secret_key_base: 1c6503dbd5ab18d3cf8efcf52f35516938a0dc377b995467ddb574d052617da99f2c9800921bcef8fe764decb6671a4b355439d8776c4dc10a8fe10cff23a410

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
